config/routes.rb
Rails.application.routes.draw do
  # resources :transactions
  # get "transactions_top_up" => "transactions#top_up", as: :top_up
  # post "transactions_top_up" => "transactions#create_top_up", as: :top_up_create
  resources :teams, :users do
    resources :transactions
    get "transactions_top_up" => "transactions#top_up", as: :top_up
    post "transactions_top_up" => "transactions#create_top_up", as: :top_up_create
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get "login" => "sessions#index", as: :login
  post "login" => "sessions#create", as: :sign_in
  get "register" => "sessions#register", as: :register
  post "register" => "sessions#sign_up", as: :sign_up

  get "logout" => "sessions#destroy", as: :logout

  # api
  namespace :api do
    post "login" => "auth#login"
    post "transfer" => "transfer#create"
    post "check_balance" => "profile#check_balance"
    get "all_profile" => "profile#all_profile"
    post "price_all" => "rapid_api#price_all"
    post "price" => "rapid_api#price"
    post "prices" => "rapid_api#prices"
  end
  # Defines the root path route ("/")
  root :to => "transactions#index"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_parent
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    @wallet = @parent.my_wallet
    @transactions = Transaction
      .where("source_wallet_address = :wallet_address OR target_wallet_address = :wallet_address", wallet_address: @wallet.wallet_address)
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @wallet = @parent.my_wallet
  end

  def top_up
    @wallet = @parent.my_wallet
    @transaction = Transaction.new
  end

  def create_top_up
    @wallet = @parent.my_wallet
    begin
      ActiveRecord::Base.transaction do
        transaction = Transaction.new(
          source_wallet_address: nil,
          target_wallet_address: @wallet.wallet_address,
          amount: params[:amount]
        )
    
        
        if transaction.save
          redirect_to polymorphic_path([@parent, :transactions]), notice: "Top up was successfully created."
        else
          render :top_up, status: :unprocessable_entity
        end
      end
    rescue => e
      render :top_up, status: :unprocessable_entity
    end
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    transaction_params = params.require(:transaction).permit(:recipient_address, :amount)
    @wallet = @parent.my_wallet

    target_wallet = Wallet.find_by(wallet_address: transaction_params[:recipient_address])
    if target_wallet.nil?
      redirect_to new_transaction_url, notice: "Recipient wallet not found."
      return
    end

    begin
      ActiveRecord::Base.transaction do
        transaction = Transaction.new(
          source_wallet_address: @wallet.wallet_address,
          target_wallet_address: transaction_params[:recipient_address],
          amount: transaction_params[:amount]
        )
    
        if transaction.save
          redirect_to polymorphic_path([@parent, :transactions]), notice: "Transaction was successfully created."
        else
          redirect_to new_polymorphic_path([@parent, :transactions]), notice: "Transaction was not created."
        end
      end
    rescue => e
      redirect_to new_polymorphic_path([@parent, :transactions]), notice: "Transaction was not created."
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy!

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      # @transaction = Transaction.find(params[:id])
    end

    def set_parent
      if params[:team_id].present?
        @parent = Team.find(params[:team_id])
      elsif params[:user_id].present?
        @parent = current_user
      else
        @parent = current_user
      end
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.fetch(:transaction, {})
    end
end

app/helpers/api/transaction_helper.rb
module Api::TransactionHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: [@parent, transaction]) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p> Balance: <%= number_to_currency(@wallet.balance) %> </p>

  <div class="form-group">
    <%= form.label :amount, class: "form-label" %>
    <%= form.number_field :amount, class: "form-control" %>
  </div>

  <div class="mt-3 form-group">
    <%= form.label :recipient_address, class: "form-label" %>
    <%= form.text_field :recipient_address, class: "form-control" %>
  </div>
  <div>
    <%= form.submit "Send Money", class: "btn btn-primary mt-3" %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <p>
    <strong>Amount:</strong>
    <%= number_to_currency(transaction.amount) %>
  </p>

  <%if transaction.source_wallet_address == @wallet.wallet_address %>
    <p>
      <strong>Transaction type:</strong>
      Sent
    </p>
    <p>
      <strong>Recipient address:</strong>
      <%= transaction.target_wallet_address %>
    </p>
  <% else %>
    <p>
      <strong>Transaction type:</strong>
      Received
    </p>

    <p>
      <strong>Sender address:</strong>
      <%= transaction.source_wallet_address %>
    </p>
  <% end %>

  <p>
    <strong>Transaction date:</strong>
    <%= transaction.created_at %>
  </p>

</div>

app/views/transactions/edit.html.erb
<% content_for :title, "Editing transaction" %>

<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Transactions" %>

<p>Balance</p>
<h1>
  <%= number_to_currency(@wallet.balance) %>
</h1>

<p>wallet address</p>
<h4>
  <%= @wallet.wallet_address %>
</h4>


<%= link_to "New transaction", new_polymorphic_path([@parent, :transaction]), class: "btn btn-primary" %>
<%= link_to "Top up", polymorphic_path([@parent, :top_up]), class: "btn btn-primary" %>
<hr>
<div id="transactions" class="mt-3">
  <p>Transactions</p>
  <% @transactions.each do |transaction| %>
      <div class="card">
        <div class="card-body">
          <%= render transaction %>
          <%= link_to "Show this transaction", polymorphic_path([@parent, transaction]) %>
        </div>
      </div>
    <p>
    </p>
  <% end %>
</div>

app/views/transactions/new.html.erb
<% content_for :title, "New transaction" %>

<p style="color: red"><%= notice %></p>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Back to transactions", polymorphic_path([@parent, :transactions]), class: "btn btn-secondary" %>
</div>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transaction %>

<div>
  <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %> |
  <%= link_to "Back to transactions", transactions_path %>

  <%= button_to "Destroy this transaction", @transaction, method: :delete %>
</div>

app/views/transactions/top_up.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Top Up" %>

<p>Balance</p>
<h1>
  <%= number_to_currency(@wallet.balance) %>
</h1>
<%= form_tag polymorphic_path([@parent, :top_up_create]), method: :post do %>
  <div class="form-group">
    <%= label_tag :amount, "Amount" %>
    <%= text_field_tag :amount, nil, class: "form-control" %>
  </div>

  <%= submit_tag "Top up", class: "btn btn-primary mt-3" %>
<% end %>

<%= link_to "Back to transactions", polymorphic_path([@parent, :transactions]), class: "btn btn-secondary mt-3" %>