config/routes.rb
Rails.application.routes.draw do
  # resources :transactions
  # get "transactions_top_up" => "transactions#top_up", as: :top_up
  # post "transactions_top_up" => "transactions#create_top_up", as: :top_up_create
  resources :teams, :users do
    resources :transactions
    get "transactions_top_up" => "transactions#top_up", as: :top_up
    post "transactions_top_up" => "transactions#create_top_up", as: :top_up_create
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get "login" => "sessions#index", as: :login
  post "login" => "sessions#create", as: :sign_in
  get "register" => "sessions#register", as: :register
  post "register" => "sessions#sign_up", as: :sign_up

  get "logout" => "sessions#destroy", as: :logout

  # api
  namespace :api do
    post "login" => "auth#login"
    post "transfer" => "transfer#create"
    post "check_balance" => "profile#check_balance"
    get "all_profile" => "profile#all_profile"
    post "price_all" => "rapid_api#price_all"
    post "price" => "rapid_api#price"
    post "prices" => "rapid_api#prices"
  end
  # Defines the root path route ("/")
  root :to => "transactions#index"
end

app/views/layouts/_dashboard.html.erb
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="#">Company name</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href=<%= logout_path %>>
        Sign out
      </a>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3 sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href=<%= users_path %>>
              <span data-feather="home" class="align-text-bottom"></span>
              Users
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href=<%= teams_path %>>
              <span data-feather="file" class="align-text-bottom"></span>
              Team
            </a>
          </li>
        </ul>

      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2"><%= content_for(:title) %></h1>
      </div>
      <%= yield %>
    </main>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Wallet Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <%# check user login %>
    <% if session[:user_id] %>
      <div id="dashboard">
        <%= render "layouts/dashboard" %>
      </div>
    <% else %>
      <div id="login">
        <%= yield %>
      </div>
    <% end %>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>

  <script>
    <%= content_for(:javascript) %>
  </script>
</html>